// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2DoemWWggm46m60yLdDAhi9eth1TaCiA',
    appId: '1:23225047246:web:c6df7f902161b9fc82589f',
    messagingSenderId: '23225047246',
    projectId: 'main-pmr',
    authDomain: 'main-pmr.firebaseapp.com',
    storageBucket: 'main-pmr.appspot.com',
    measurementId: 'G-PC0JL2VRVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFeXE57J4YrHd97nv7Mt7MbfqlJ-PtKsE',
    appId: '1:23225047246:android:279e5a77fe2c601f82589f',
    messagingSenderId: '23225047246',
    projectId: 'main-pmr',
    storageBucket: 'main-pmr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCymo1ZftF1DETfie8n5qQMMhe5ejw09rE',
    appId: '1:23225047246:ios:012768ef1e0ffcfe82589f',
    messagingSenderId: '23225047246',
    projectId: 'main-pmr',
    storageBucket: 'main-pmr.appspot.com',
    iosBundleId: 'com.example.mainFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCymo1ZftF1DETfie8n5qQMMhe5ejw09rE',
    appId: '1:23225047246:ios:012768ef1e0ffcfe82589f',
    messagingSenderId: '23225047246',
    projectId: 'main-pmr',
    storageBucket: 'main-pmr.appspot.com',
    iosBundleId: 'com.example.mainFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2DoemWWggm46m60yLdDAhi9eth1TaCiA',
    appId: '1:23225047246:web:e53c5a20cbea28bc82589f',
    messagingSenderId: '23225047246',
    projectId: 'main-pmr',
    authDomain: 'main-pmr.firebaseapp.com',
    storageBucket: 'main-pmr.appspot.com',
    measurementId: 'G-XEHE84LL0F',
  );
}
